# Auto-generated by synthedge — do not edit manually
# Source: C:\Users\georg\OneDrive\Desktop\Projects\synthetic-edge-generator\.claude\worktrees\mvp-d1-d14\operations.py
# Re-run `synthedge` to refresh these tests

import pytest
import sys
import os

# Ensure the target module is importable
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from operations import *


def test_synthedge_add_type_error_000():
    """
    Found by synthedge: add raises TypeError
    Input: (None, '')
    Error: TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
    """
    with pytest.raises(TypeError):
        add(*(None, ''))

def test_synthedge_add_type_error_001():
    """
    Found by synthedge: add raises TypeError
    Input: ('', nan)
    Error: TypeError: can only concatenate str (not "float") to str
    """
    with pytest.raises(TypeError):
        add(*('', nan))

def test_synthedge_divide_type_error_002():
    """
    Found by synthedge: divide raises TypeError
    Input: ('', 0)
    Error: TypeError: Numerator must be numeric
    """
    with pytest.raises(TypeError):
        divide(*('', 0))

def test_synthedge_divide_type_error_003():
    """
    Found by synthedge: divide raises TypeError
    Input: (0, '')
    Error: TypeError: Denominator must be numeric
    """
    with pytest.raises(TypeError):
        divide(*(0, ''))

def test_synthedge_multiply_type_error_004():
    """
    Found by synthedge: multiply raises TypeError
    Input: (None, 0)
    Error: TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
    """
    with pytest.raises(TypeError):
        multiply(*(None, 0))

def test_synthedge_multiply_type_error_005():
    """
    Found by synthedge: multiply raises TypeError
    Input: (0, '')
    Error: TypeError: must be real number, not str
    """
    with pytest.raises(TypeError):
        multiply(*(0, ''))

def test_synthedge_multiply_type_error_006():
    """
    Found by synthedge: multiply raises TypeError
    Input: ('', nan)
    Error: TypeError: can't multiply sequence by non-int of type 'float'
    """
    with pytest.raises(TypeError):
        multiply(*('', nan))

def test_synthedge_add_type_error_007():
    """
    Found by synthedge: add raises TypeError
    Input: ('', 0)
    Error: TypeError: can only concatenate str (not "int") to str
    """
    with pytest.raises(TypeError):
        add(*('', 0))

def test_synthedge_add_type_error_008():
    """
    Found by synthedge: add raises TypeError
    Input: ('', None)
    Error: TypeError: can only concatenate str (not "NoneType") to str
    """
    with pytest.raises(TypeError):
        add(*('', None))

def test_synthedge_multiply_type_error_009():
    """
    Found by synthedge: multiply raises TypeError
    Input: ('', 'string')
    Error: TypeError: can't multiply sequence by non-int of type 'str'
    """
    with pytest.raises(TypeError):
        multiply(*('', 'string'))

def test_synthedge_multiply_type_error_010():
    """
    Found by synthedge: multiply raises TypeError
    Input: (None, '')
    Error: TypeError: can't multiply sequence by non-int of type 'NoneType'
    """
    with pytest.raises(TypeError):
        multiply(*(None, ''))
