import os
from typing import Any, Dict, List

from edge_case_engine.deduplicator import CrashDeduplicator
from edge_case_engine.minimizer import InputMinimizer


class PytestExporter:

    @staticmethod
    def export(
        crashes: List[Dict[str, Any]],
        module_path: str,
        function_registry: Dict[str, Any],
        output_path: str,
    ) -> int:
        """
        Generate a pytest file from deduplicated crashes.

        crashes: list of {input, error, severity} dicts (already deduplicated)
        module_path: path to the fuzzed module (for import statement)
        function_registry: {function_name: callable} for minimization
        output_path: where to write the pytest file

        Returns: number of test cases written
        """
        if not crashes:
            return 0

        module_name = os.path.splitext(os.path.basename(module_path))[0]
        lines = PytestExporter._build_header(module_name, module_path)

        for i, crash in enumerate(crashes):
            test_fn = PytestExporter._build_test_function(
                crash=crash,
                index=i,
                function_registry=function_registry,
            )
            lines.extend(test_fn)
            lines.append("")

        content = "\n".join(lines)
        with open(output_path, "w") as f:
            f.write(content)

        return len(crashes)

    @staticmethod
    def _build_header(module_name: str, module_path: str) -> list:
        abs_path = os.path.abspath(module_path)
        return [
            "# Auto-generated by synthedge — do not edit manually",
            f"# Source: {abs_path}",
            "# Re-run `synthedge` to refresh these tests",
            "",
            "import pytest",
            "import sys",
            "import os",
            "",
            "# Ensure the target module is importable",
            f"sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))",
            f"from {module_name} import *",
            "",
            "",
        ]

    @staticmethod
    def _build_test_function(
        crash: Dict[str, Any],
        index: int,
        function_registry: Dict[str, Any],
    ) -> list:
        raw_input = crash.get("input", ())
        error_str = crash.get("error", "Exception")

        # Parse error type from stored string "ExcType: message"
        parts = error_str.split(":", 1)
        exc_type = parts[0].strip() if len(parts) > 1 else "Exception"
        exc_msg_raw = parts[1].strip() if len(parts) > 1 else error_str

        # Sanitize exc_type so it is always a valid Python identifier
        # (guards against multi-word or weird strings becoming invalid syntax)
        if not exc_type.isidentifier():
            exc_type = "Exception"

        # Try to find a function name from the registry that matches
        func_name = PytestExporter._infer_function_name(raw_input, error_str, function_registry)

        # Attempt minimization if we have the function
        minimized_input = raw_input
        if func_name and func_name in function_registry:
            func = function_registry[func_name]
            sig = CrashDeduplicator.signature(exc_msg_raw)
            try:
                minimized_input = InputMinimizer.minimize(
                    func=func,
                    original_input=tuple(raw_input) if not isinstance(raw_input, tuple) else raw_input,
                    expected_error_sig=sig,
                )
            except Exception:
                minimized_input = raw_input

        # Build a safe test name
        safe_exc = exc_type.lower().replace("error", "_error").replace(" ", "_")
        # Strip any characters that are not alphanumeric or underscore
        safe_exc = "".join(c if c.isalnum() or c == "_" else "_" for c in safe_exc)
        safe_func = func_name or "unknown"
        safe_func = "".join(c if c.isalnum() or c == "_" else "_" for c in safe_func)
        test_name = f"test_synthedge_{safe_func}_{safe_exc}_{index:03d}"

        # Repr the input safely
        if not isinstance(minimized_input, tuple):
            minimized_input = tuple(minimized_input) if hasattr(minimized_input, "__iter__") else (minimized_input,)
        input_repr = repr(minimized_input)

        lines = [
            f"def {test_name}():",
            f'    """',
            f'    Found by synthedge: {func_name or "unknown function"} raises {exc_type}',
            f'    Input: {input_repr}',
            f'    Error: {error_str[:120]}',
            f'    """',
            f"    with pytest.raises({exc_type}):",
            f"        {safe_func}(*{input_repr})",
        ]
        return lines

    @staticmethod
    def _infer_function_name(
        raw_input: Any,
        error_str: str,
        function_registry: Dict[str, Any],
    ) -> str:
        """Pick the most likely function: try each registered function with the input."""
        for name, func in function_registry.items():
            try:
                args = tuple(raw_input) if not isinstance(raw_input, tuple) else raw_input
                func(*args)
            except Exception as e:
                candidate_str = f"{type(e).__name__}: {e}"
                if candidate_str == error_str:
                    return name
            except Exception:
                pass
        # Fall back to first registered function
        return next(iter(function_registry), "unknown")
